from pathlib import Path

def write(path: str, content: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

write('docs/DEPLOYMENT.md', '# Deployment\n\n## Local Docker Compose\n\n1. Copy `.env.example` to `.env`.\n2. Generate independent API and admin keys with `python scripts/generate_api_key.py`.\n3. Set the two keys in `.env`.\n4. Run `docker compose up --build`.\n5. Open `http://localhost:8000/docs`.\n\nCompose starts PostgreSQL, Redis, the FastAPI API, and a Celery worker. API and worker share a Docker volume for model artifacts.\n\n## Render or another multi-service host\n\nUse the included `render.yaml` as a starting point. A web service and worker cannot generally rely on separate local disks for shared model files. Configure an S3-compatible object store and set the same values on both processes:\n\n- `MODEL_STORE_URI=s3://your-bucket/weather-models`\n- `AWS_REGION`\n- `AWS_ACCESS_KEY_ID`\n- `AWS_SECRET_ACCESS_KEY`\n- Optional `S3_ENDPOINT_URL` for non-AWS S3-compatible storage\n\nSet `DATABASE_URL` to PostgreSQL, `REDIS_URL` to Redis, and `TASK_ALWAYS_EAGER=false`.\n\nFor a one-process pilot, omit the worker, set `TASK_ALWAYS_EAGER=true`, and mount persistent storage at `MODEL_STORE_URI`. This is simpler but unsuitable for large training jobs.\n\n## Required production secrets\n\n- `ML_SERVICE_API_KEYS`\n- `ADMIN_API_KEY`\n- Database and Redis credentials\n- Object-store credentials when a worker is used\n\n## Health checks\n\n- `/health`: process health, public and non-sensitive\n- `/ready`: verifies database connectivity\n- `/v1/model-health`: authenticated champion/artifact/model status\n- `/metrics`: Prometheus format when enabled\n')
write('docs/TRAINING_DATA_CONTRACT.md', '# Training data contract\n\nThe service accepts CSV or Parquet. It normalizes common aliases, but a production dataset should use these canonical fields.\n\n## Required\n\n| Field | Type | Meaning |\n|---|---:|---|\n| `target_time` | ISO-8601 timestamp | Time/date the settled weather value applies to. |\n| `actual_value` | number | Official observed settlement-compatible value. |\n| `forecast_mean` | number | Forecast value available at prediction time. |\n| `station_code` | string | Exact settlement station identifier. |\n| `market_type` | string | For example `daily_high_temperature`. |\n\n## Strongly recommended\n\n`latitude`, `longitude`, `elevation_m`, `lead_hours`, `forecast_median`, `forecast_std`, `forecast_min`, `forecast_max`, `latest_temperature`, `observation_trend_1h`, `dew_point`, `humidity`, `wind_speed`, `wind_direction_sin`, `wind_direction_cos`, `cloud_cover`, `pressure`, `precipitation_probability`, `model_count`, and `data_age_seconds`.\n\n## Contract/backtest fields\n\nAdd `lower_bound`, `upper_bound`, and `market_yes_ask` to train probability calibration on real market brackets and backtest tradable signals. Bounds use an inclusive lower edge and exclusive upper edge. A blank lower edge means “below upper”; a blank upper edge means “at or above lower.” Prices are decimal dollars from 0 to 1.\n\n## Non-negotiable timestamp rule\n\nA feature may only contain information that was available at the historical prediction timestamp. Preserve forecast issue/availability time separately in the source warehouse even if the flattened model table only contains `lead_hours`. Never replace old forecast records with revised forecasts.\n\n## Settlement alignment\n\nFor production training, `actual_value` should come from the exact source and station named by the Kalshi contract. The built-in Open-Meteo route is a bootstrap mechanism and deliberately labels its dataset with a warning because gridded reanalysis is not identical to every official settlement station.\n')
write('docs/lovable-client.ts', 'import { supabase } from "@/integrations/supabase/client";\n\nexport type MlAction =\n  | "modelHealth"\n  | "modelVersions"\n  | "predictMarket"\n  | "explainPrediction"\n  | "listStations"\n  | "listDatasets"\n  | "createBacktest"\n  | "getBacktest"\n  | "getTrainingJob"\n  | "trainCandidate"\n  | "evaluateCandidate"\n  | "promoteModel"\n  | "rollbackModel"\n  | "recordOutcome";\n\nexport async function callMlService<T>(\n  action: MlAction,\n  payload?: unknown,\n  id?: string,\n): Promise<T> {\n  const { data, error } = await supabase.functions.invoke("ml-service", {\n    body: { action, payload, id },\n  });\n  if (error) {\n    throw new Error(error.message || "ML service request failed");\n  }\n  return data as T;\n}\n')
