from pathlib import Path

def write(path: str, content: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

write('app/core/config.py', 'from __future__ import annotations\n\nimport json\nfrom functools import lru_cache\nfrom pathlib import Path\n\nfrom pydantic import field_validator\nfrom pydantic_settings import BaseSettings, SettingsConfigDict\n\n\nclass Settings(BaseSettings):\n    model_config = SettingsConfigDict(\n        env_file=".env",\n        env_file_encoding="utf-8",\n        extra="ignore",\n        case_sensitive=False,\n    )\n\n    app_name: str = "Kalshi Weather ML Service"\n    app_env: str = "development"\n    log_level: str = "INFO"\n    api_prefix: str = "/v1"\n\n    ml_service_api_keys: str = ""\n    admin_api_key: str = ""\n\n    database_url: str = "sqlite:///./data/weather_ml.sqlite3"\n    redis_url: str = "redis://localhost:6379/0"\n    task_always_eager: bool = True\n\n    model_store_uri: str = "./artifacts"\n    active_model_cache_seconds: int = 60\n    min_data_quality_score: float = 0.70\n    max_input_data_age_seconds: int = 7200\n    min_training_rows: int = 250\n\n    rate_limit_requests: int = 240\n    rate_limit_window_seconds: int = 60\n    cors_origins: list[str] = []\n    trusted_hosts: list[str] = ["*"]\n\n    open_meteo_archive_url: str = "https://archive-api.open-meteo.com/v1/archive"\n    open_meteo_historical_forecast_url: str = (\n        "https://historical-forecast-api.open-meteo.com/v1/forecast"\n    )\n    nws_api_url: str = "https://api.weather.gov"\n    http_user_agent: str = "kalshi-weather-ml-service/1.0 contact@example.com"\n    http_timeout_seconds: int = 45\n\n    s3_endpoint_url: str | None = None\n    aws_region: str = "us-east-1"\n    aws_access_key_id: str | None = None\n    aws_secret_access_key: str | None = None\n\n    prometheus_enabled: bool = True\n    auto_create_tables: bool = True\n\n    @field_validator("cors_origins", "trusted_hosts", mode="before")\n    @classmethod\n    def parse_json_list(cls, value: object) -> object:\n        if isinstance(value, str):\n            value = value.strip()\n            if not value:\n                return []\n            if value.startswith("["):\n                return json.loads(value)\n            return [item.strip() for item in value.split(",") if item.strip()]\n        return value\n\n    @property\n    def api_keys(self) -> list[str]:\n        return [key.strip() for key in self.ml_service_api_keys.split(",") if key.strip()]\n\n    @property\n    def model_store_path(self) -> Path:\n        return Path(self.model_store_uri).expanduser().resolve()\n\n    @property\n    def is_production(self) -> bool:\n        return self.app_env.lower() == "production"\n\n\n@lru_cache(maxsize=1)\ndef get_settings() -> Settings:\n    return Settings()\n')
write('app/core/exceptions.py', 'from __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom typing import Any\n\n\n@dataclass\nclass ServiceError(Exception):\n    code: str\n    message: str\n    status_code: int = 400\n    details: dict[str, Any] | None = None\n\n    def as_detail(self) -> dict[str, Any]:\n        payload: dict[str, Any] = {"code": self.code, "message": self.message}\n        if self.details:\n            payload["details"] = self.details\n        return payload\n')
write('app/core/logging.py', 'from __future__ import annotations\n\nimport json\nimport logging\nimport sys\nfrom datetime import UTC, datetime\nfrom typing import Any\n\nfrom app.core.config import get_settings\n\n\nclass JsonFormatter(logging.Formatter):\n    def format(self, record: logging.LogRecord) -> str:\n        payload: dict[str, Any] = {\n            "timestamp": datetime.now(UTC).isoformat(),\n            "level": record.levelname,\n            "logger": record.name,\n            "message": record.getMessage(),\n        }\n        for field in ("request_id", "path", "method", "status_code", "duration_ms"):\n            value = getattr(record, field, None)\n            if value is not None:\n                payload[field] = value\n        if record.exc_info:\n            payload["exception"] = self.formatException(record.exc_info)\n        return json.dumps(payload, default=str)\n\n\ndef configure_logging() -> None:\n    settings = get_settings()\n    handler = logging.StreamHandler(sys.stdout)\n    handler.setFormatter(JsonFormatter())\n    root = logging.getLogger()\n    root.handlers.clear()\n    root.addHandler(handler)\n    root.setLevel(settings.log_level.upper())\n')
