from pathlib import Path

def write(path: str, content: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

write('alembic/env.py', 'from __future__ import annotations\n\nfrom logging.config import fileConfig\n\nfrom alembic import context\nfrom sqlalchemy import engine_from_config, pool\n\nfrom app.core.config import get_settings\nfrom app.db.base import Base\nfrom app.db import models  # noqa: F401\n\nconfig = context.config\nif config.config_file_name is not None:\n    fileConfig(config.config_file_name)\nconfig.set_main_option("sqlalchemy.url", get_settings().database_url)\ntarget_metadata = Base.metadata\n\n\ndef run_migrations_offline() -> None:\n    context.configure(\n        url=config.get_main_option("sqlalchemy.url"),\n        target_metadata=target_metadata,\n        literal_binds=True,\n        dialect_opts={"paramstyle": "named"},\n        compare_type=True,\n    )\n    with context.begin_transaction():\n        context.run_migrations()\n\n\ndef run_migrations_online() -> None:\n    connectable = engine_from_config(\n        config.get_section(config.config_ini_section, {}),\n        prefix="sqlalchemy.",\n        poolclass=pool.NullPool,\n    )\n    with connectable.connect() as connection:\n        context.configure(connection=connection, target_metadata=target_metadata, compare_type=True)\n        with context.begin_transaction():\n            context.run_migrations()\n\n\nif context.is_offline_mode():\n    run_migrations_offline()\nelse:\n    run_migrations_online()\n')
write('alembic/versions/0001_initial.py', '\"\"\"initial schema\n\nRevision ID: 0001_initial\nRevises:\nCreate Date: 2026-07-01\n\"\"\"\n\nfrom alembic import op\n\nfrom app.db.base import Base\nfrom app.db import models  # noqa: F401\n\nrevision = "0001_initial"\ndown_revision = None\nbranch_labels = None\ndepends_on = None\n\n\ndef upgrade() -> None:\n    Base.metadata.create_all(bind=op.get_bind())\n\n\ndef downgrade() -> None:\n    Base.metadata.drop_all(bind=op.get_bind())\n')
write('alembic.ini', '[alembic]\nscript_location = alembic\nprepend_sys_path = .\nsqlalchemy.url = sqlite:///./data/weather_ml.sqlite3\n\n[loggers]\nkeys = root,sqlalchemy,alembic\n[handlers]\nkeys = console\n[formatters]\nkeys = generic\n\n[logger_root]\nlevel = WARN\nhandlers = console\nqualname =\n\n[logger_sqlalchemy]\nlevel = WARN\nhandlers =\nqualname = sqlalchemy.engine\n\n[logger_alembic]\nlevel = INFO\nhandlers =\nqualname = alembic\n\n[handler_console]\nclass = StreamHandler\nargs = (sys.stderr,)\nlevel = NOTSET\nformatter = generic\n\n[formatter_generic]\nformat = %(levelname)-5.5s [%(name)s] %(message)s\ndatefmt = %H:%M:%S\n')
write('app/__init__.py', '')
write('app/api/__init__.py', '')
write('app/api/deps.py', 'from app.core.security import ApiPrincipal, require_admin_key, require_api_key\nfrom app.db.session import get_db\n\n__all__ = ["ApiPrincipal", "require_api_key", "require_admin_key", "get_db"]\n')
write('app/api/routes/__init__.py', '')
write('app/api/routes/backtests.py', 'from __future__ import annotations\n\nfrom fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status\nfrom sqlalchemy.orm import Session\n\nfrom app.api.deps import ApiPrincipal, get_db, require_api_key\nfrom app.core.config import get_settings\nfrom app.db.models import BacktestRun, DatasetManifest\nfrom app.schemas.backtest import BacktestRequest, BacktestRunRead\nfrom app.services.backtest_service import execute_backtest\nfrom app.services.model_service import get_model_record\nfrom app.workers.tasks import run_backtest_task\n\nrouter = APIRouter(prefix="/backtests", tags=["backtests"])\n\n\ndef _execute_local(run_id: str) -> None:\n    from app.db.session import SessionLocal\n\n    with SessionLocal() as db:\n        execute_backtest(db, run_id)\n\n\n@router.post("", response_model=BacktestRunRead, status_code=status.HTTP_202_ACCEPTED)\ndef create_backtest(\n    payload: BacktestRequest,\n    background_tasks: BackgroundTasks,\n    db: Session = Depends(get_db),\n    _: ApiPrincipal = Depends(require_api_key),\n) -> BacktestRunRead:\n    if db.get(DatasetManifest, payload.dataset_id) is None:\n        raise HTTPException(status_code=404, detail={"code": "DATASET_NOT_FOUND", "message": payload.dataset_id})\n    try:\n        model = get_model_record(db, payload.model_version)\n    except LookupError as exc:\n        raise HTTPException(status_code=404, detail={"code": "MODEL_NOT_FOUND", "message": str(exc)}) from exc\n    configuration = payload.model_dump(exclude={"dataset_id", "model_version"})\n    run = BacktestRun(dataset_id=payload.dataset_id, model_version_id=model.id, configuration=configuration)\n    db.add(run)\n    db.commit()\n    db.refresh(run)\n    if get_settings().task_always_eager:\n        background_tasks.add_task(_execute_local, run.id)\n    else:\n        run_backtest_task.delay(run.id)\n    return BacktestRunRead.model_validate(run)\n\n\n@router.get("/{run_id}", response_model=BacktestRunRead)\ndef get_backtest(\n    run_id: str,\n    db: Session = Depends(get_db),\n    _: ApiPrincipal = Depends(require_api_key),\n) -> BacktestRunRead:\n    run = db.get(BacktestRun, run_id)\n    if run is None:\n        raise HTTPException(status_code=404, detail={"code": "BACKTEST_NOT_FOUND", "message": run_id})\n    return BacktestRunRead.model_validate(run)\n')
