from pathlib import Path

def write(path: str, content: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

write('render.yaml', 'services:\n  - type: web\n    name: kalshi-weather-ml-api\n    runtime: docker\n    dockerfilePath: ./Dockerfile\n    healthCheckPath: /health\n    envVars:\n      - key: APP_ENV\n        value: production\n      - key: ML_SERVICE_API_KEYS\n        sync: false\n      - key: ADMIN_API_KEY\n        sync: false\n      - key: DATABASE_URL\n        fromDatabase:\n          name: kalshi-weather-ml-db\n          property: connectionString\n      - key: REDIS_URL\n        fromService:\n          type: redis\n          name: kalshi-weather-ml-redis\n          property: connectionString\n      - key: TASK_ALWAYS_EAGER\n        value: "false"\n      - key: MODEL_STORE_URI\n        sync: false\n      - key: AWS_REGION\n        sync: false\n      - key: AWS_ACCESS_KEY_ID\n        sync: false\n      - key: AWS_SECRET_ACCESS_KEY\n        sync: false\n      - key: S3_ENDPOINT_URL\n        sync: false\n\n  - type: worker\n    name: kalshi-weather-ml-worker\n    runtime: docker\n    dockerfilePath: ./Dockerfile\n    dockerCommand: celery -A app.workers.celery_app:celery_app worker --loglevel=INFO --concurrency=2\n    envVars:\n      - key: APP_ENV\n        value: production\n      - key: ML_SERVICE_API_KEYS\n        sync: false\n      - key: ADMIN_API_KEY\n        sync: false\n      - key: DATABASE_URL\n        fromDatabase:\n          name: kalshi-weather-ml-db\n          property: connectionString\n      - key: REDIS_URL\n        fromService:\n          type: redis\n          name: kalshi-weather-ml-redis\n          property: connectionString\n      - key: TASK_ALWAYS_EAGER\n        value: "false"\n      - key: MODEL_STORE_URI\n        sync: false\n      - key: AWS_REGION\n        sync: false\n      - key: AWS_ACCESS_KEY_ID\n        sync: false\n      - key: AWS_SECRET_ACCESS_KEY\n        sync: false\n      - key: S3_ENDPOINT_URL\n        sync: false\n\n  - type: redis\n    name: kalshi-weather-ml-redis\n    ipAllowList: []\n    plan: starter\n\ndatabases:\n  - name: kalshi-weather-ml-db\n    plan: basic-256mb\n')
write('requirements.txt', '-e .\n')
write('scripts/generate_api_key.py', 'from __future__ import annotations\n\nimport secrets\n\nif __name__ == "__main__":\n    print(secrets.token_urlsafe(48))\n')
write('scripts/generate_demo_data.py', '\"\"\"Generate synthetic data for smoke tests only. Never use this output to justify live trading.\"\"\"\n\nfrom __future__ import annotations\n\nimport argparse\nfrom pathlib import Path\n\nimport numpy as np\nimport pandas as pd\n\n\ndef main() -> None:\n    parser = argparse.ArgumentParser()\n    parser.add_argument("--rows", type=int, default=1200)\n    parser.add_argument("--output", default="data/demo_training.csv")\n    args = parser.parse_args()\n    rng = np.random.default_rng(42)\n    dates = pd.date_range("2021-01-01", periods=args.rows, freq="D", tz="UTC")\n    seasonal = 62 + 24 * np.sin(2 * np.pi * (dates.dayofyear - 170) / 365.25)\n    forecast = seasonal + rng.normal(0, 2.4, args.rows)\n    actual = forecast + rng.normal(0, 2.0, args.rows) + 0.8 * np.sin(2 * np.pi * dates.dayofyear / 30)\n    lower = np.floor(forecast / 2) * 2\n    frame = pd.DataFrame(\n        {\n            "target_time": dates,\n            "station_code": "DEMO",\n            "market_type": "daily_high_temperature",\n            "latitude": 40.78,\n            "longitude": -73.97,\n            "elevation_m": 43,\n            "lead_hours": 24,\n            "forecast_mean": forecast,\n            "forecast_median": forecast,\n            "forecast_std": 2.0,\n            "forecast_min": forecast - 2.5,\n            "forecast_max": forecast + 2.5,\n            "latest_temperature": forecast - rng.normal(5, 2, args.rows),\n            "humidity": rng.uniform(35, 95, args.rows),\n            "wind_speed": rng.uniform(0, 20, args.rows),\n            "cloud_cover": rng.uniform(0, 100, args.rows),\n            "actual_value": actual,\n            "lower_bound": lower,\n            "upper_bound": lower + 2,\n            "market_yes_ask": np.clip(rng.normal(0.45, 0.14, args.rows), 0.05, 0.95),\n        }\n    )\n    path = Path(args.output)\n    path.parent.mkdir(parents=True, exist_ok=True)\n    frame.to_csv(path, index=False)\n    print(path)\n\n\nif __name__ == "__main__":\n    main()\n')
