from pathlib import Path

def write(path: str, content: str) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

write('config/stations.example.json', '[\n  {\n    "station_code": "KNYC",\n    "station_name": "Central Park",\n    "latitude": 40.77898,\n    "longitude": -73.96925,\n    "elevation_m": 42.7,\n    "timezone": "America/New_York",\n    "official_source": "NWS/NOAA"\n  },\n  {\n    "station_code": "KJFK",\n    "station_name": "John F. Kennedy International Airport",\n    "latitude": 40.6398,\n    "longitude": -73.7789,\n    "elevation_m": 3.9,\n    "timezone": "America/New_York",\n    "official_source": "NWS/NOAA"\n  }\n]\n')
write('data/.gitkeep', '')
write('docker-compose.yml', 'services:\n  postgres:\n    image: postgres:17-alpine\n    environment:\n      POSTGRES_DB: weather_ml\n      POSTGRES_USER: weather_ml\n      POSTGRES_PASSWORD: weather_ml_local\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U weather_ml -d weather_ml"]\n      interval: 5s\n      timeout: 5s\n      retries: 20\n    volumes:\n      - postgres_data:/var/lib/postgresql/data\n\n  redis:\n    image: redis:7-alpine\n    command: ["redis-server", "--appendonly", "yes"]\n    healthcheck:\n      test: ["CMD", "redis-cli", "ping"]\n      interval: 5s\n      timeout: 3s\n      retries: 20\n    volumes:\n      - redis_data:/data\n\n  api:\n    build: .\n    env_file: .env\n    environment:\n      DATABASE_URL: postgresql+psycopg://weather_ml:weather_ml_local@postgres:5432/weather_ml\n      REDIS_URL: redis://redis:6379/0\n      TASK_ALWAYS_EAGER: "false"\n      MODEL_STORE_URI: /srv/app/artifacts\n    ports:\n      - "8000:8000"\n    depends_on:\n      postgres:\n        condition: service_healthy\n      redis:\n        condition: service_healthy\n    volumes:\n      - model_artifacts:/srv/app/artifacts\n\n  worker:\n    build: .\n    command: ["celery", "-A", "app.workers.celery_app:celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]\n    env_file: .env\n    environment:\n      DATABASE_URL: postgresql+psycopg://weather_ml:weather_ml_local@postgres:5432/weather_ml\n      REDIS_URL: redis://redis:6379/0\n      TASK_ALWAYS_EAGER: "false"\n      MODEL_STORE_URI: /srv/app/artifacts\n    depends_on:\n      postgres:\n        condition: service_healthy\n      redis:\n        condition: service_healthy\n    volumes:\n      - model_artifacts:/srv/app/artifacts\n\nvolumes:\n  postgres_data:\n  redis_data:\n  model_artifacts:\n')
write('pyproject.toml', '[build-system]\nrequires = ["setuptools>=75", "wheel"]\nbuild-backend = "setuptools.build_meta"\n\n[project]\nname = "kalshi-weather-ml-service"\nversion = "1.0.0"\ndescription = "Production-oriented weather probability, calibration, backtesting, and model-registry API for Kalshi-connected applications."\nrequires-python = ">=3.12,<3.14"\ndependencies = [\n  "fastapi==0.128.2",\n  "uvicorn[standard]==0.48.0",\n  "pydantic==2.13.4",\n  "pydantic-settings==2.14.1",\n  "sqlalchemy==2.0.50",\n  "alembic==1.18.4",\n  "psycopg[binary]==3.3.3",\n  "numpy==2.3.5",\n  "pandas==2.2.3",\n  "scikit-learn==1.8.0",\n  "joblib==1.5.3",\n  "httpx==0.28.1",\n  "python-multipart==0.0.22",\n  "celery==5.6.2",\n  "redis==7.4.0",\n  "prometheus-client==0.24.1",\n  "orjson==3.11.7",\n  "boto3==1.42.58",\n]\n\n[project.optional-dependencies]\ndev = [\n  "pytest==9.0.2",\n  "pytest-cov==7.0.0",\n  "ruff==0.15.5",\n  "mypy==1.19.1",\n]\n\n[project.scripts]\nweather-ml = "app.cli:main"\n\n[tool.setuptools.packages.find]\ninclude = ["app*"]\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\naddopts = "-q --disable-warnings"\n\n[tool.ruff]\ntarget-version = "py312"\nline-length = 100\nexclude = ["alembic/versions"]\n\n[tool.ruff.lint]\nselect = ["E", "F", "I", "B", "UP", "SIM"]\nignore = ["B008", "E501"]\n\n[tool.mypy]\npython_version = "3.12"\nplugins = ["pydantic.mypy"]\nignore_missing_imports = true\nwarn_unused_ignores = true\n\n[tool.coverage.run]\nsource = ["app"]\nomit = ["app/workers/*"]\n')
